### PR TITLE
add DateGenerated stamp to the generated file headers

### PR DESCRIPTION
**Pull request by james-trayford**
Add `DateGenerated` stamp to the `Header` attributes, to allow useful errors in SWIFT

### CODE REVIEW

**Comment by correac** [comment]
Great James! Merging this now..

**Comment by MatthieuSchaller** [comment]
Could you also regenerate the tables in `/data/` ? I see they are still 15 days old and hence don't have the date string.

**Comment by james-trayford** [comment]
@MatthieuSchaller @correac ah yes I missed the fact we were tracking the output files too - perhaps easiest is either to run the code to generate the tables or if Camila can run the code and push the new tables directly to the `main` branch?

**Comment by correac** [comment]
@MatthieuSchaller  @james-trayford  Yes, I just run the code and push the new tables.

**Pull request merged**
